#!/bin/bash

if [ $# == 0 ]; then
    echo "Usage: launch <filename>"
    exit
fi

for i in "$@"; 
do
    extension="${i##*.}"

    case $extension in
        "pdf")
            evince $i &
            ;;
        "txt" | "md")
            subl $i
            ;;
        *)
            xdg-open $i &
            ;;
    esac
done
