#!/bin/bash

echo "TV Section Scan"
curl "http://127.0.0.1:32400/library/sections/2/refresh?force=0&X-Plex-Token=pmctSQ9xusD6voGB1BHE"

echo "Movie Section Scan"
curl "http://127.0.0.1:32400/library/sections/1/refresh?force=0&X-Plex-Token=pmctSQ9xusD6voGB1BHE"